/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.importing;

import dao.InvoiceDAO;
import model.Invoice;
import view.user.ManagerHomeFrm;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author Shisui
 */
public class ConfirmFrm extends javax.swing.JFrame implements ActionListener {
    Invoice i;

    /**
     * Creates new form Confirm
     */
    public ConfirmFrm(Invoice i) {
        initComponents();
        this.i = i;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.getHSBColor(106, 52, 50));
        this.setLayout(null);

        this.lblNo.setText(i.getNo());
        // format date: dd/MM/yyyy
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String formattedDate = sdf.format(i.getDate());
        this.lblDate.setText(formattedDate);
        this.lblSName.setText(i.getSupplier().getName());
        this.lblSAddress.setText(i.getSupplier().getAddress());
        this.lblSTel.setText(i.getSupplier().getTel());
        this.lblSTaxCode.setText(i.getSupplier().getTaxCode());
        this.lblIName.setText(i.getBuyer().getFullname());
        this.lblIRole.setText(i.getBuyer().getRole());
        DecimalFormat df = new DecimalFormat("#,###");
        DefaultTableModel model = (DefaultTableModel) this.tblImportedMaterial.getModel();
        for (int j = 0; j < i.getListMaterial().size(); j++) {
            model.addRow(new Object[]{
                i.getListMaterial().get(j).getMaterial().getId(),
                i.getListMaterial().get(j).getMaterial().getName(),
                i.getListMaterial().get(j).getQuantity(),
                i.getListMaterial().get(j).getUnitPrice(),
                i.getListMaterial().get(j).getQuantity() * i.getListMaterial().get(j).getUnitPrice()
            });
        }
        this.lblSubtotal.setText(df.format(i.getTotalAmount()) + " VNĐ");
        this.lblTax.setText(String.format("%.2f", i.getTax()) + "%");
        double taxPrice = i.getTotalAmount() * i.getTax() / 100;
        this.lblTaxPrice.setText(df.format(taxPrice) + " VNĐ");
        this.lblTotal.setText(df.format(i.getTotalAmount() + taxPrice) + " VNĐ");
        this.lblRemaining.setText("0 VNĐ");
        

        this.btnConfirm.addActionListener(this);
        this.btnCancel.addActionListener(this);
        this.btnAdd.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrm = new javax.swing.JLabel();
        lblSupplier = new javax.swing.JLabel();
        lblFSName = new javax.swing.JLabel();
        lblSName = new javax.swing.JLabel();
        lblFSAddress = new javax.swing.JLabel();
        lblSAddress = new javax.swing.JLabel();
        lblFSTel = new javax.swing.JLabel();
        lblSTel = new javax.swing.JLabel();
        lblFSTaxCode = new javax.swing.JLabel();
        lblSTaxCode = new javax.swing.JLabel();
        lblImporter = new javax.swing.JLabel();
        lblFIName = new javax.swing.JLabel();
        lblIName = new javax.swing.JLabel();
        lblFIRole = new javax.swing.JLabel();
        lblIRole = new javax.swing.JLabel();
        lblFNo = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblFDate = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblImportedMaterial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImportedMaterial = new javax.swing.JTable();
        txtFSubtotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblFTax = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblFTaxPrice = new javax.swing.JLabel();
        lblTaxPrice = new javax.swing.JLabel();
        lblFTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblFPaid = new javax.swing.JLabel();
        lblFRemaining = new javax.swing.JLabel();
        lblRemaining = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFrm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblFrm.setText("Confirm Importing");

        lblSupplier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSupplier.setText("Supplier Information:");

        lblFSName.setText("Name:");

        lblSName.setText("Gorgeous");

        lblFSAddress.setText("Address:");

        lblSAddress.setText("29 P. Bà Triệu, Hàng Bài, Hoàn Kiếm, Hà Nội");

        lblFSTel.setText("Tel:");

        lblSTel.setText("035626962");

        lblFSTaxCode.setText("Tax code:");

        lblSTaxCode.setText("0316265669");

        lblImporter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImporter.setText("Importer:");

        lblFIName.setText("Name:");

        lblIName.setText("Nguyen Dang Quang");

        lblFIRole.setText("Role:");

        lblIRole.setText("Manager");

        lblFNo.setText("Invoice No:");

        lblNo.setText("12345");

        lblFDate.setText("Date:");

        lblDate.setText("27/04/2023");

        lblImportedMaterial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblImportedMaterial.setText("Imported Materials:");

        tblImportedMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Unit Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblImportedMaterial);

        txtFSubtotal.setText("Subtotal:");

        lblSubtotal.setText("3.674.000  VNĐ");

        lblFTax.setText("Tax:");

        lblTax.setText("10%");

        lblFTaxPrice.setText("Tax price:");

        lblTaxPrice.setText("334.000 VNĐ");

        lblFTotal.setText("Total:");

        lblTotal.setText("3.674.000 VNĐ");

        lblFPaid.setText("Paid amount:");

        lblFRemaining.setText("Remaining amount: ");

        lblRemaining.setText("0 VNĐ");

        btnAdd.setText("Add");

        btnConfirm.setText("Confirm");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFrm)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFNo)
                                            .addComponent(lblFDate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblFSAddress)
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblSTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblSAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)))
                                    .addComponent(lblSupplier, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblFSName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(lblSName, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFSTel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFSTaxCode))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSTaxCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblImportedMaterial, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGap(312, 312, 312))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblImporter)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFIRole, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblIRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFIName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblIName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(26, 26, 26))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFPaid)
                                    .addGap(55, 55, 55)
                                    .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblFTax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFSubtotal)
                                        .addComponent(lblFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(78, 78, 78)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFRemaining)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAdd)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFTaxPrice)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblTaxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblFrm)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFNo)
                    .addComponent(lblNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFDate)
                    .addComponent(lblDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSupplier)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFSName)
                            .addComponent(lblSName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFSAddress)
                            .addComponent(lblSAddress)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImporter)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFIName)
                            .addComponent(lblIName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFIRole)
                            .addComponent(lblIRole))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFSTel)
                    .addComponent(lblSTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFSTaxCode)
                    .addComponent(lblSTaxCode))
                .addGap(27, 27, 27)
                .addComponent(lblImportedMaterial)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(txtFSubtotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFTax)
                    .addComponent(lblTax)
                    .addComponent(lblFTaxPrice)
                    .addComponent(lblTaxPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFTotal)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFPaid)
                    .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFRemaining)
                    .addComponent(lblRemaining))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmFrm(new Invoice()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFDate;
    private javax.swing.JLabel lblFIName;
    private javax.swing.JLabel lblFIRole;
    private javax.swing.JLabel lblFNo;
    private javax.swing.JLabel lblFPaid;
    private javax.swing.JLabel lblFRemaining;
    private javax.swing.JLabel lblFSAddress;
    private javax.swing.JLabel lblFSName;
    private javax.swing.JLabel lblFSTaxCode;
    private javax.swing.JLabel lblFSTel;
    private javax.swing.JLabel lblFTax;
    private javax.swing.JLabel lblFTaxPrice;
    private javax.swing.JLabel lblFTotal;
    private javax.swing.JLabel lblFrm;
    private javax.swing.JLabel lblIName;
    private javax.swing.JLabel lblIRole;
    private javax.swing.JLabel lblImportedMaterial;
    private javax.swing.JLabel lblImporter;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JLabel lblSAddress;
    private javax.swing.JLabel lblSName;
    private javax.swing.JLabel lblSTaxCode;
    private javax.swing.JLabel lblSTel;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTaxPrice;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblImportedMaterial;
    private javax.swing.JLabel txtFSubtotal;
    private javax.swing.JTextField txtPaid;

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnAdd) {
            String paid = txtPaid.getText();
            if (paid.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter the paid amount!");
                return;
            }
            double paidAmount = Double.parseDouble(paid);
            if (paidAmount < i.getTotalAmount()) {
                JOptionPane.showMessageDialog(this, "The paid amount must be greater than or equal to the total amount!");
                return;
            }
            i.setPaidAmount(paidAmount);
            DecimalFormat df = new DecimalFormat("#,###");
            this.lblRemaining.setText(df.format(paidAmount - (i.getTotalAmount() + i.getTotalAmount() * i.getTax() / 100)) + " VNĐ");
        } else if (e.getSource() == btnConfirm) {
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to import this invoice?", "Confirm importing", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
            InvoiceDAO id = new InvoiceDAO();
            if(!id.addInvoice(i)) {
                JOptionPane.showMessageDialog(this, "Importing failed! Please try again.");
                return;
            }
            JOptionPane.showMessageDialog(this, "Importing successfully!");
            ManagerHomeFrm managerHomeFrm = new ManagerHomeFrm(i.getBuyer());
            managerHomeFrm.setVisible(true);
            this.dispose();
        } else if (e.getSource() == btnCancel) {
            int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel the importing?", "Cancel importing", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                ManagerHomeFrm managerHomeFrm = new ManagerHomeFrm(i.getBuyer());
                managerHomeFrm.setVisible(true);
                this.dispose();
            }
        }
    }
    // End of variables declaration//GEN-END:variables
}
